import sys
import os
from config import *

def create():
	project_name = str(sys.argv[1])
	project_path = path + project_name
	print('\"{}\"'.format(project_path))
	os.makedirs(project_path)
	os.chdir(project_path)
	os.system('echo \"First commit\" > README.md')
	os.system('git init')
	os.system('git add .')
	os.system('git commit -m \"initial commit\"')
	# Creates the remote repo in GitHub
	request = '\
curl -i -X POST -H "Authorization: token 27a69e787357bd7a78ecc5145509602b1c886ff8" \
-d \"{\\"name\\":\\"'+project_name+'\\", \\"description\\":\\"Project autogenerated\\"}\" https://api.github.com/user/repos'
	os.system(request)

	os.system('git remote add origin git@github.com:{}/{}.git'.format(username, project_name))
	os.system('git push -u origin master')


if __name__ == "__main__":
	create()
